# Generated by Django 6.1.1 on 2026-09-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C'), ('html', 'HTML')], max_length=10)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('submitted', 'Submitted'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('judge0_output', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('problem_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.problemstatement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
