# Generated by Django 6.1.1 on 2026-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('go', 'Go'), ('java', 'Java'), ('javascript', 'JavaScript'), ('python', 'Python'), ('rust', 'Rust'), ('html', 'HTML')], max_length=10),
        ),
    ]
