# Generated by Django 6.1.1 on 2026-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
