# Generated by Django 6.1.1 on 2026-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
